[providers]
php = "8.2"

[variables]
PORT = "8080"

[phases.setup]
nixPkgs = ["php82"]

[phases.install]
cmds = ["mkdir -p /var/log/nginx", "mkdir -p /var/cache/nginx"]

[start]
cmd = "php -S 0.0.0.0:$PORT" 